### ISSUE TITLE
什么时候能支持python2

### ISSUE THREAD

**Issue by feixiangdao** [aploium/shootback#2]
如题

**Comment by aploium** [comment]
在10月20号以后, 11月以前
同时会把slaver整合成一个文件, 并且放弃选择使用配置文件的方式, 使用命令行参数调用

**Comment by feixiangdao** [comment]
期待，毕竟还是很多使用python2的

2016-10-08 12:02 GMT+08:00 Aploium <notifications@github.com>:

**Comment by aploium** [comment]
已经完成代码的重写, 支持单文件slaver, py27支持, 命令行调用
